Context: do not let close() throw Exception
The dispose() method does not throw exceptions, and we do not need to throw
one when auto-closing. This prevents the compilation error:

  Unhandled exception type Exception thrown by automatic close() invocation on context

which occurs with code of the form:

  try (Context context = new Context()) {
    ...
  }