Revert commit "Use List instead of Iterable as returntype of the ModuleInfo methods returning list of ModuleItems."
This reverts commit 88d3cab189d1fd68b2065e0e109cbb18ef48e0b0.

Unfortunately, this change results in incompatible bytecode, such that
downstream callers encounter exceptions like:

    java.lang.NoSuchMethodError: org.scijava.module.ModuleInfo.inputs()Ljava/lang/Iterable;
            at net.imagej.ops.NamespacePreprocessor.process(NamespacePreprocessor.java:56)
            at org.scijava.module.ModuleRunner.preProcess(ModuleRunner.java:104)

So this change will need to wait till SciJava Common 3.0.0, sadly.