Add a regression test for urlToFile(directory)
Java on Windows really has problems in that department: the default
AppClassLoader is a URLClassLoader whose getURLs() method returns URLs
of the form:

	file:C:/path/to/file.jar

i.e. omitting a slash: it should read

	file:/C:/path/to/file.jar

instead, otherwise, when converted into a URI via the toURI() method,
then passed onto a File constructor, one will see the lovely message:

	IllegalArgumentException: URI is not hierarchical

Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>